import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { MyProvider } from "./redux/provider";

const popins = Poppins({ subsets: ["latin"], weight: "300" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={popins.className + " bg-[#FFFFFF]"}>
        <MyProvider child={children} />
      </body>
    </html>
  );
}
